# Generated by Django 3.1.8 on 2021-05-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, null=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование курса')),
                ('description', models.TextField(blank=True, verbose_name='Информация о курсе')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('price', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Наименование курса',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя преподавателя')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст преподавателя')),
                ('phone', models.IntegerField(blank=True, verbose_name='Номер мобильного телефона')),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя студента')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст студента')),
                ('phone', models.IntegerField(blank=True, verbose_name='Номер мобильного телефона')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(blank=True, verbose_name='Успеваемость студента')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.courses', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['name'],
            },
        ),
    ]
