# Generated by Django 3.1.8 on 2021-04-27 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210427_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
