# Generated by Django 3.1.8 on 2021-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210427_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='courses',
            name='methods',
            field=models.TextField(default=1, verbose_name='Методика обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='questions',
            field=models.TextField(default=1, verbose_name='Часто задаваемые вопросы'),
            preserve_default=False,
        ),
    ]
